components:
  schemas:

    Config:
      description: |-
        ONEx dataflow configuration
      type: object
      properties:
        hosts:
          type: array
          items:
            $ref: "../model/host/host.yaml#/components/schemas/Host"
        dataflow:
            $ref: "../model/dataflow/dataflow.yaml#/components/schemas/Dataflow"
        eth_nic_profiles:
          type: array
          items:
            $ref: '../model/profiles/eth_nic_settings.yaml#/components/schemas/Profiles.Dataflow.HostManagement.EthNicSetting'

    GetConfigDetails:
      description: |-
        Get config request details
      type: object

    Experiment.Request:
      description: |-
        Experiment request details
      type: object

    Control.Start.Request:
      description: |-
        Start request details
      type: object


    Control.Status.Request:
      description: |-
        control.state request details
      type: object

    Control.Status.Response:
      description: |-
        control/state response details
      type: object
      properties:
        dataflow_status:
          description: |-
            dataflow status:
            started - data flow traffic is running
            completed - all traffic flows completed, metrics are available
            error - an error occurred
          type: string
          enum: [started, completed, error]
        errors:
          type: array
          items:
            $ref: "../common/common.yaml#/components/schemas/Error.Item"

    Metrics.Request:
      description: |-
        Metrics request details
      type: object

    Metrics.Response:
      description: |-
        Metrics response details
      type: object
      properties:
        jct:
          description: job completion time in micro seconds
          type: integer
          format: int64
        flow_results:
          type: array
          items:
            $ref: '#/components/schemas/Metrics.Response.FlowResult'

    Metrics.Response.FlowResult:
      description: result for a single data flow
      properties:
        workload_name:
          type: string
        from_host_name:
          type: string
        to_host_name:
          type: string
        fct:
          type: integer
          format: int64
          description: flow completion time in micro seconds
        first_timestamp:
          type: integer
          format: int64
          description: first timestamp in micro seconds
        last_timestamp:
          type: integer
          format: int64
          description: last timestamp in micro seconds          
        bytes_tx:
          type: integer
          format: int64
          description: bytes transmitted from src to dst
        bytes_rx:
          type: integer
          format: int64
          description: bytes received by src from dst
        tcp_info_initiator:
          $ref: "#/components/schemas/Metrics.Response.FlowResult.TcpInfo"
        tcp_info_responder:
          $ref: "#/components/schemas/Metrics.Response.FlowResult.TcpInfo"          

    Metrics.Response.FlowResult.TcpInfo:
      type: object
      description: TCP information for this flow
      properties:
        rtt:
          type: integer
          format: int64
          description: average round trip time in microseconds
        rtt_variance:
          type: integer
          format: int64
          description: round trip time variance in microseconds, larger values indicate less stable performance
        retransmissions:
          type: integer
          format: int64
          description: total number of TCP retransmissions
        retransmission_timeout:
          type: integer
          format: int64
          description: retransmission timeout in micro seconds
        congestion_window:
          type: integer
          format: int64
          description: congestion windows size in bytes
        slow_start_threshold:
          type: integer
          format: int64
          description: slow start threshold in bytes (max int64 value when wide open)
        path_mtu:
          type: integer
          format: int64
          description: path MTU




